name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip python3-pip libncurses5-dev || sudo apt-get install -y git zip unzip python3-pip libncurses6

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
        export PATH=$PATH:~/.buildozer/android/platform/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"
        
        # Ensure AIDL is available by adding build-tools to PATH
        export ANDROID_HOME=$HOME/.buildozer/android/platform
        export PATH=$PATH:$ANDROID_HOME/build-tools/31.0.0

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform
        export PATH=$PATH:$HOME/.buildozer/android/platform/cmdline-tools/latest/bin
        export PATH=$PATH:$ANDROID_HOME/build-tools/31.0.0
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-android-apk
        path: bin/*.apk
        retention-days: 30
