name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip unzip \
          openjdk-17-jdk \
          python3-pip \
          python3.10-venv \
          libffi-dev \
          libssl-dev \
          libz-dev \
          libjpeg-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libfreetype6-dev \
          pkg-config

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install cython buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: bin/*.apk
