name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip python3-pip \
          build-essential libffi-dev libssl-dev \
          zlib1g-dev libbz2-dev libreadline-dev \
          libsqlite3-dev wget curl llvm \
          libncurses5-dev libncursesw5-dev \
          xz-utils tk-dev liblzma-dev \
          python3-openssl autoconf libtool \
          pkg-config cmake ninja-build \
          ccache ant gradle openjdk-11-jdk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install buildozer==1.5.0 cython==0.29.33
        pip install colorama appdirs sh jinja2 six

    - name: Setup Android SDK Commandline Tools and Build Tools
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools

        cd $ANDROID_SDK_ROOT
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d cmdline-tools

        # Move extracted folder to 'latest' for consistency
        mv cmdline-tools/cmdline-tools cmdline-tools/latest

        # Add both possible sdkmanager paths to PATH
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$PATH

        # Verify sdkmanager exists
        if [ ! -f "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ] && [ ! -f "$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager" ]; then
          echo "ERROR: sdkmanager not found!"
          exit 1
        fi

        # Accept licenses
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || yes | $ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager --licenses

        # Install platform-tools, platforms and build-tools (30.0.3 includes aidl)
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;30.0.3" || $ANDROID_SDK_ROOT/cmdline-tools/tools/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;30.0.3"

        # Check aidl exists
        if [ -f "$ANDROID_SDK_ROOT/build-tools/30.0.3/aidl" ]; then
          echo "aidl found!"
        else
          echo "ERROR: aidl NOT found!"
          exit 1
        fi

        # Export paths for buildozer
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/build-tools/30.0.3" >> $GITHUB_PATH

    - name: Setup buildozer environment
      run: |
        mkdir -p ~/.buildozer/android
        ln -sf $ANDROID_SDK_ROOT ~/.buildozer/android/platform
        buildozer init || echo "buildozer.spec already exists."

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/build-tools/30.0.3:$PATH
        export PYTHONUNBUFFERED=1
        export P4A_RELEASE_KEYSTORE=$HOME/debug.keystore
        export P4A_RELEASE_KEYALIAS=androiddebugkey
        export P4A_RELEASE_KEYSTORE_PASSWD=android
        export P4A_RELEASE_KEYALIAS_PASSWD=android

        # Generate debug keystore if missing
        if [ ! -f "$P4A_RELEASE_KEYSTORE" ]; then
          keytool -genkey -v -keystore $P4A_RELEASE_KEYSTORE -alias androiddebugkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US" \
            -storepass android -keypass android
        fi

        buildozer android debug --verbose

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: lime-offline-unlocker-debug
        path: bin/*.apk
        retention-days: 30

    - name: Upload build logs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs-failure
        path: .buildozer/
        retention-days: 7
