name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install system dependencies
      run: |
        echo "Updating apt-get and installing system dependencies..."
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip python3-pip \
          build-essential libffi-dev libssl-dev \
          zlib1g-dev libbz2-dev libreadline-dev \
          libsqlite3-dev wget curl llvm \
          libncurses5-dev libncursesw5-dev \
          xz-utils tk-dev liblzma-dev \
          python3-openssl autoconf libtool \
          pkg-config cmake ninja-build \
          ccache ant gradle

    - name: Install Python dependencies
      run: |
        echo "Installing Python dependencies..."
        python -m pip install --upgrade pip wheel setuptools
        pip install buildozer==1.5.0 cython==0.29.33
        pip install colorama appdirs sh jinja2 six

    - name: Setup Android SDK
      run: |
        # Define Android SDK root path
        SDK_ROOT_PATH=$HOME/android-sdk
        
        # Create directory and navigate into it
        echo "Creating Android SDK directory at $SDK_ROOT_PATH..."
        mkdir -p $SDK_ROOT_PATH
        cd $SDK_ROOT_PATH
        
        # Download command line tools
        echo "Downloading Android command-line tools..."
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Move extracted tools to the 'latest' subdirectory for proper sdkmanager functionality
        mkdir -p cmdline-tools/latest
        # The unzip likely creates a 'cmdline-tools' directory. We want its contents moved.
        mv cmdline-tools/* cmdline-tools/latest/ || true # Use '|| true' to prevent script from failing if mv finds no matches
        
        # Add primary SDK tools to PATH for the current shell session and future steps
        echo "Adding Android SDK command-line tools to PATH..."
        export PATH=$PATH:$SDK_ROOT_PATH/cmdline-tools/latest/bin
        export PATH=$PATH:$SDK_ROOT_PATH/platform-tools
        
        # Accept licenses
        echo "Accepting Android SDK licenses..."
        yes | sdkmanager --licenses
        
        # Install required SDK packages for Buildozer
        echo "Installing Android SDK packages (platform-tools, platforms;android-31, build-tools;31.0.0)..."
        sdkmanager \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0"
        
        # IMPORTANT: Persist environment variables for subsequent steps using GITHUB_ENV and GITHUB_PATH
        echo "Persisting Android SDK environment variables for subsequent steps..."
        echo "ANDROID_SDK_ROOT=$SDK_ROOT_PATH" >> $GITHUB_ENV
        echo "ANDROID_HOME=$SDK_ROOT_PATH" >> $GITHUB_ENV # Buildozer often uses ANDROID_HOME
        echo "$SDK_ROOT_PATH/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$SDK_ROOT_PATH/platform-tools" >> $GITHUB_PATH
        echo "$SDK_ROOT_PATH/build-tools/31.0.0" >> $GITHUB_PATH

    - name: Setup buildozer
      run: |
        echo "Setting up Buildozer environment..."
        # Create buildozer directory and link Android SDK
        mkdir -p ~/.buildozer/android
        # Buildozer looks for the platform directory, linking ANDROID_HOME is common.
        ln -sf $ANDROID_HOME ~/.buildozer/android/platform
        
        # Initialize buildozer config file if it doesn't exist
        # This will create a buildozer.spec if not present in the repository
        buildozer init || echo "Buildozer already initialized or buildozer.spec exists."

    - name: Fix AIDL Path
      run: |
        echo "Checking and fixing AIDL path..."
        # AIDL is typically found in build-tools.
        # Buildozer often handles this, but this step acts as a safeguard.
        # Ensure the path corresponds to the installed build tools version.
        AIDL_BUILD_TOOLS_PATH="$ANDROID_HOME/build-tools/31.0.0"
        AIDL_PATH="$AIDL_BUILD_TOOLS_PATH/aidl"
        
        if [ -f "$AIDL_PATH" ]; then
          echo "AIDL found at $AIDL_PATH. Adding build tools to PATH."
          echo "$AIDL_BUILD_TOOLS_PATH" >> $GITHUB_PATH
        else
          echo "AIDL not found for build-tools 31.0.0. Attempting to install build-tools 30.0.3 as a fallback."
          # If 31.0.0 AIDL is not found, try installing 30.0.3, which is sometimes a common alternative for Kivy
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3"
          echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH
        fi

    - name: Build APK
      run: |
        echo "Starting APK build with Buildozer..."
        # These environment variables are already persisted from previous steps via GITHUB_ENV and GITHUB_PATH
        # Setting them again here is redundant but harmless. Removed for clarity.
        
        export PYTHONUNBUFFERED=1 # Important for unbuffered output during build
        
        # Define debug keystore paths and passwords
        # Ensure this keystore is safe for your use case; this is for debug builds.
        export P4A_RELEASE_KEYSTORE=$HOME/debug.keystore
        export P4A_RELEASE_KEYALIAS=androiddebugkey
        export P4A_RELEASE_KEYSTORE_PASSWD=android
        export P4A_RELEASE_KEYALIAS_PASSWD=android
        
        # Generate debug keystore if it doesn't exist
        if [ ! -f "$P4A_RELEASE_KEYSTORE" ]; then
          echo "Generating debug keystore..."
          keytool -genkey -v -keystore $P4A_RELEASE_KEYSTORE -alias androiddebugkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US" \
            -storepass android -keypass android
          echo "Debug keystore generated at $P4A_RELEASE_KEYSTORE"
        else
          echo "Debug keystore already exists at $P4A_RELEASE_KEYSTORE"
        fi
        
        # Build with verbose output for detailed logs
        buildozer android debug --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: lime-offline-unlocker-debug
        path: bin/*.apk
        retention-days: 30

    - name: Upload logs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs-failure
        path: |
          .buildozer/
        retention-days: 7
