name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev \
                            libz-dev libncurses5 libsqlite3-dev libgmp-dev \
                            build-essential git wget

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Set up Android SDK manually
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/
        export PATH=$HOME/.buildozer/android/platform/cmdline-tools/latest/bin:$PATH
        yes | $HOME/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"

    - name: Build APK
      run: |
        export PATH=$HOME/.buildozer/android/platform/cmdline-tools/latest/bin:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-android-apk
        path: bin/*.apk
        retention-days: 30
